spring.profiles.active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5482/postgres
    username: postgres
    password: postgres5
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
