spring.profiles.active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5482/postgres
    username: pgroot
    password: pgpass
liquibase:
  change-log: classpath:/liquibase/db-changelog.xml
